project_id = "vrprqzrykonusfsvegwk"

[functions.generate-dpp]
enabled = true
verify_jwt = false
import_map = "./functions/generate-dpp/deno.json"
entrypoint = "./functions/generate-dpp/index.ts"

[functions.activate-student]
enabled = true
verify_jwt = false

[functions.create-student]
enabled = true
verify_jwt = false

[functions.create-admin]
enabled = true
verify_jwt = false

