import type { DPP, StudentProfile } from './types';

export const initialStudentProfile: StudentProfile = {
  name: 'Shubham Kumar',
  rollNo: 'NA-2026-0002',
  batch: 'Dhurandar',
  streak: 5,
  xp: 320,
  unlockedBadges: ['Kinematics Specialist', 'Formula Master'],
};

export const mockDpps: DPP[] = [
  {
    id: 'dpp-101',
    topicId: 'physics-kinematics-1',
    name: '1D Kinematics & Solitary Calculus',
    subject: 'Physics',
    totalQuestions: 5,
    batch: 'Dhurandar',
    dueDate: '2026-07-20',
    estimatedTime: 15,
    questions: [
      {
        id: 'q-p-1',
        question: 'A particle moves along a straight line such that its velocity $v$ at time $t$ is given by $v(t) = 3t^2 - 2t + 4$ m/s. Find the acceleration of the particle at $t = 3$ seconds.',
        options: [
          '16 m/s$^2$',
          '20 m/s$^2$',
          '14 m/s$^2$',
          '18 m/s$^2$',
        ],
        correctAnswer: 'A',
        explanation: 'Acceleration $a(t)$ is the first derivative of velocity with respect to time: \n$$a(t) = \\frac{dv}{dt} = \\frac{d}{dt}(3t^2 - 2t + 4) = 6t - 2$$\n\nSubstituting $t = 3$ s:\n$$a(3) = 6(3) - 2 = 18 - 2 = 16 \\text{ m/s}^2$$\n\nHence, option A is correct.',
        difficulty: 'Easy',
        estimatedTimeSeconds: 120,
        marks: 4,
        learningOutcome: 'Differentiation-based 1D acceleration calculations.',
      },
      {
        id: 'q-p-2',
        question: 'A ball is projected vertically upwards with a velocity of $u = 20$ m/s from the top of a tower of height $h = 25$ m. How long does it take for the ball to strike the ground? (Take $g = 10$ m/s$^2$)',
        options: [
          '3 seconds',
          '4 seconds',
          '5 seconds',
          '6 seconds',
        ],
        correctAnswer: 'C',
        explanation: 'Using the displacement equation with downward as negative: \n$$s = ut + \\frac{1}{2}at^2$$\n\nHere, displacement $s = -25$ m, initial velocity $u = +20$ m/s, and acceleration $a = -g = -10$ m/s$^2$.\n$$-25 = 20t - 5t^2 \\implies 5t^2 - 20t - 25 = 0 \\implies t^2 - 4t - 5 = 0$$\n\nFactoring the quadratic:\n$$(t - 5)(t + 1) = 0$$\n\nSince time cannot be negative, $t = 5$ seconds.\n\nOption C is the correct answer.',
        difficulty: 'Medium',
        estimatedTimeSeconds: 180,
        marks: 4,
        learningOutcome: 'Vertical project motion under gravity.',
      },
      {
        id: 'q-p-3',
        question: 'The position of a particle is given by $x(t) = A\\cos(\\omega t)$. What is the magnitude of the maximum acceleration of the particle?',
        options: [
          '$A\\omega$',
          '$A\\omega^2$',
          '$A^2\\omega$',
          '$A\\omega^3$',
        ],
        correctAnswer: 'B',
        explanation: 'Position: $x(t) = A\\cos(\\omega t)$\n\nVelocity $v(t)$ is the first derivative:\n$$v(t) = \\frac{dx}{dt} = -A\\omega\\sin(\\omega t)$$\n\nAcceleration $a(t)$ is the second derivative:\n$$a(t) = \\frac{dv}{dt} = -A\\omega^2\\cos(\\omega t)$$\n\nThe maximum magnitude occurs when $|\\cos(\\omega t)| = 1$:\n$$a_{\\max} = A\\omega^2$$\n\nTherefore, option B is correct.',
        difficulty: 'Medium',
        estimatedTimeSeconds: 150,
        marks: 4,
        learningOutcome: 'Acceleration amplitude in Simple Harmonic Motion.',
      },
      {
        id: 'q-p-4',
        question: 'A vehicle decelerates from $v = 15$ m/s to rest over a distance of $30$ m. Assuming uniform deceleration, what is the deceleration magnitude?',
        options: [
          '3.75 m/s$^2$',
          '2.5 m/s$^2$',
          '5.0 m/s$^2$',
          '1.85 m/s$^2$',
        ],
        correctAnswer: 'A',
        explanation: 'We use the equation: \n$$v^2 = u^2 + 2as$$\n\nGiven final velocity $v = 0$, initial velocity $u = 15$ m/s, and displacement $s = 30$ m:\n$$0 = 15^2 + 2(a)(30) \\implies 60a = -225 \\implies a = -3.75 \\text{ m/s}^2$$\n\nHence, the magnitude of deceleration is $3.75$ m/s$^2$, matching option A.',
        difficulty: 'Easy',
        estimatedTimeSeconds: 120,
        marks: 4,
        learningOutcome: 'Constant acceleration equations.',
      },
      {
        id: 'q-p-5',
        question: 'An object starts from rest and moves with acceleration $a(t) = \\alpha t$, where $\\alpha = 2$ m/s$^3$. Find the total displacement of the object after $t = 3$ seconds.',
        options: [
          '6 meters',
          '9 meters',
          '12 meters',
          '18 meters',
        ],
        correctAnswer: 'B',
        explanation: 'First, find the velocity $v(t)$ by integrating $a(t)$:\n$$v(t) = \\int a(t)dt = \\int 2t\\,dt = t^2 + C_1$$\n\nSince the object starts from rest, $v(0) = 0 \\implies C_1 = 0$, so $v(t) = t^2$.\n\nNext, integrate velocity to find displacement $s(t)$:\n$$s(t) = \\int v(t)dt = \\int t^2\\,dt = \\frac{t^3}{3} + C_2$$\n\nAssuming $s(0) = 0 \\implies C_2 = 0$, so $s(t) = \\frac{t^3}{3}$.\n\nSubstituting $t = 3$ s:\n$$s(3) = \\frac{3^3}{3} = 9 \\text{ meters}$$\n\nHence, option B is correct.',
        difficulty: 'Hard',
        estimatedTimeSeconds: 240,
        marks: 4,
        learningOutcome: 'Double integration under variable acceleration.',
      },
    ],
  },
  {
    id: 'dpp-102',
    topicId: 'biology-kidney-1',
    name: 'Excretory Products & Elimination: Nephron Function',
    subject: 'Biology',
    totalQuestions: 3,
    batch: 'Dhurandar',
    dueDate: '2026-07-22',
    estimatedTime: 10,
    questions: [
      {
        id: 'q-b-1',
        question: 'Which of the following parts of the nephron is highly permeable to water but almost impermeable to electrolytes, leading to the concentration of filtrate?',
        options: [
          'Ascending limb of Henle\'s loop',
          'Descending limb of Henle\'s loop',
          'Distal Convoluted Tubule (DCT)',
          'Proximal Convoluted Tubule (PCT)',
        ],
        correctAnswer: 'B',
        explanation: 'The **descending limb of Henle\'s loop** is permeable to water but almost completely impermeable to electrolytes. As filtrate flows down, water is drawn out osmotiaclly into the hypertonic medullary interstitium, concentrating the tubular fluid.\n\nIn contrast, the **ascending limb** is impermeable to water but active/passive reabsorbs electrolytes, diluting the filtrate.\n\nOption B is correct.',
        difficulty: 'Easy',
        estimatedTimeSeconds: 90,
        marks: 4,
        learningOutcome: 'Osmoregulation mechanics in Henle\'s Loop.',
      },
      {
        id: 'q-b-2',
        question: 'Under low blood pressure conditions, the Juxtaglomerular Apparatus (JGA) releases Renin. Renin initiates a cascade converting angiotensinogen to angiotensin I and subsequently angiotensin II. What is the primary physiological action of angiotensin II?',
        options: [
          'It acts as a powerful vasodilator decreasing GFR.',
          'It stimulates the adrenal cortex to secrete Aldosterone.',
          'It inhibits ADH secretion from the posterior pituitary.',
          'It decreases sodium reabsorption in the renal tubules.',
        ],
        correctAnswer: 'B',
        explanation: 'Angiotensin II is a potent vasoconstrictor that increases glomerular filtration pressure (GFR). It also stimulates the **adrenal cortex** to release **Aldosterone**, which increases sodium and water reabsorption in the distal tubules. Additionally, it stimulates thirst and ADH release to restore blood volume and pressure.\n\nOption B is correct.',
        difficulty: 'Medium',
        estimatedTimeSeconds: 120,
        marks: 4,
        learningOutcome: 'Renin-Angiotensin-Aldosterone System (RAAS) regulation.',
      },
      {
        id: 'q-b-3',
        question: 'What is the main physiological mechanism behind Ultrafiltration in the Bowman\'s capsule?',
        options: [
          'Active transport of urea via membrane protein carriers.',
          'Hydrostatic pressure gradient opposing colloidal osmotic pressure.',
          'Simple diffusion of large plasma proteins through slit pores.',
          'Facilitated diffusion of blood cells into the PCT lumen.',
        ],
        correctAnswer: 'B',
        explanation: 'Ultrafiltration is a passive process driven by the **glomerular hydrostatic pressure** (approx $60$ mmHg), which forces fluid through the three-layered filtration membrane. This pressure is opposed by the **blood colloidal osmotic pressure** (approx $32$ mmHg) and the **capsular hydrostatic pressure** (approx $18$ mmHg). Large proteins and blood cells cannot pass due to size-exclusion slit pores.\n\nOption B is the correct physiological description.',
        difficulty: 'Hard',
        estimatedTimeSeconds: 150,
        marks: 4,
        learningOutcome: 'Bowman Capsule hydrostatic and colloid filtration dynamics.',
      },
    ],
  },
  {
    id: 'dpp-103',
    topicId: 'maths-integration-1',
    name: 'Definite Integration & Areas under Curves',
    subject: 'Mathematics',
    totalQuestions: 4,
    batch: 'Veera',
    dueDate: '2026-07-25',
    estimatedTime: 20,
    questions: [
      {
        id: 'q-m-1',
        question: 'Evaluate the definite integral:\n$$\\int_{0}^{\\pi/2} \\frac{\\sin x}{\\sin x + \\cos x} \\, dx$$',
        options: [
          '$\\pi/2$',
          '$\\pi/4$',
          '$\\pi/8$',
          '$\\pi$',
        ],
        correctAnswer: 'B',
        explanation: 'Let $I = \\int_{0}^{\\pi/2} \\frac{\\sin x}{\\sin x + \\cos x} \\, dx$. \nUsing King\'s Property: $\\int_{a}^{b} f(x)\\,dx = \\int_{a}^{b} f(a+b-x)\\,dx$:\n$$I = \\int_{0}^{\\pi/2} \\frac{\\sin(\\pi/2 - x)}{\\sin(\\pi/2 - x) + \\cos(\\pi/2 - x)} \\, dx = \\int_{0}^{\\pi/2} \\frac{\\cos x}{\\cos x + \\sin x} \\, dx$$\n\nAdding the two equations:\n$$2I = \\int_{0}^{\\pi/2} \\frac{\\sin x + \\cos x}{\\sin x + \\cos x} \\, dx = \\int_{0}^{\\pi/2} 1 \\, dx = [x]_{0}^{\\pi/2} = \\frac{\\pi}{2}$$\n\n$$I = \\frac{\\pi}{4}$$\n\nOption B is correct.',
        difficulty: 'Medium',
        estimatedTimeSeconds: 180,
        marks: 4,
        learningOutcome: 'Symmetric bounds properties of integration.',
      },
      {
        id: 'q-m-2',
        question: 'Find the area of the region bounded by the parabola $y^2 = 4x$ and the line $y = 2x$.',
        options: [
          '$1/3$',
          '$2/3$',
          '$1/2$',
          '$1$',
        ],
        correctAnswer: 'A',
        explanation: 'Find the intersection points by substituting $y = 2x$ into the parabola equation:\n$$(2x)^2 = 4x \\implies 4x^2 - 4x = 0 \\implies 4x(x - 1) = 0$$\n\nIntersection coordinates are at $x = 0$ (where $y=0$) and $x = 1$ (where $y=2$).\nFor $x \\in [0, 1]$, the parabola is above the line, so the area $A$ is:\n$$A = \\int_{0}^{1} (\\sqrt{4x} - 2x) \\, dx = \\int_{0}^{1} (2x^{1/2} - 2x) \\, dx$$\n\n$$A = \\left[ \\frac{4}{3}x^{3/2} - x^2 \\right]_{0}^{1} = \\frac{4}{3} - 1 = \\frac{1}{3}$$\n\nHence, option A is correct.',
        difficulty: 'Medium',
        estimatedTimeSeconds: 210,
        marks: 4,
        learningOutcome: 'Area between intersecting linear-quadratic bounds.',
      },
      {
        id: 'q-m-3',
        question: 'What is the value of the integral:\n$$\\int_{-1}^{1} x|x| \\, dx$$',
        options: [
          '$2/3$',
          '$0$',
          '$-2/3$',
          '$1/3$',
        ],
        correctAnswer: 'B',
        explanation: 'Let $f(x) = x|x|$.\nTest for odd/even function:\n$$f(-x) = (-x)|-x| = -x|x| = -f(x)$$\n\nSince $f(x)$ is an odd function, integrating it over symmetric limits $[-a, a]$ yields $0$:\n$$\\int_{-1}^{1} x|x| \\, dx = 0$$\n\nOption B is correct.',
        difficulty: 'Easy',
        estimatedTimeSeconds: 90,
        marks: 4,
        learningOutcome: 'Integration of odd functions over symmetric bounds.',
      },
      {
        id: 'q-m-4',
        question: 'Evaluate:\n$$\\lim_{n \\to \\infty} \\sum_{r=1}^{n} \\frac{n}{n^2 + r^2}$$',
        options: [
          '$\\pi/4$',
          '$\\pi/2$',
          '$1$',
          '$\\ln 2$',
        ],
        correctAnswer: 'A',
        explanation: 'Express the limit of the sum as a definite integral:\n$$\\lim_{n \\to \\infty} \\frac{1}{n} \\sum_{r=1}^{n} \\frac{1}{1 + (r/n)^2}$$\n\nLet $\\frac{r}{n} = x$, $\\frac{1}{n} = dx$, and the integration limits are from $0$ (for $r=0$) to $1$ (for $r=n$):\n$$I = \\int_{0}^{1} \\frac{1}{1 + x^2} \\, dx = \\left[ \\tan^{-1} x \\right]_{0}^{1} = \\tan^{-1}(1) - \\tan^{-1}(0) = \\frac{\\pi}{4}$$\n\nOption A is correct.',
        difficulty: 'Hard',
        estimatedTimeSeconds: 240,
        marks: 4,
        learningOutcome: 'Converting Riemann limit sums to definite integrals.',
      },
    ],
  },
];
