// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLAXCUIQAsC_0oAxc9GHcaJsZKMVWezBA',
    appId: '1:450723447835:web:7fc3770a2078f945b764be',
    messagingSenderId: '450723447835',
    projectId: 'national-academy-c0441',
    authDomain: 'national-academy-c0441.firebaseapp.com',
    storageBucket: 'national-academy-c0441.firebasestorage.app',
    measurementId: 'G-QE5KZZHJ8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKa9qZTdyLN3DVs62xnCf6XUxd-QHIZX0',
    appId: '1:450723447835:android:b1d5eb76a86e7e6cb764be',
    messagingSenderId: '450723447835',
    projectId: 'national-academy-c0441',
    storageBucket: 'national-academy-c0441.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyQ-jzGMcvBm4a4rKZjXiCyam16KNXKRI',
    appId: '1:450723447835:ios:aadad851989dd175b764be',
    messagingSenderId: '450723447835',
    projectId: 'national-academy-c0441',
    storageBucket: 'national-academy-c0441.firebasestorage.app',
    iosClientId: '450723447835-5avf10vt5v9ddfcj10781ku5ia0q8bnj.apps.googleusercontent.com',
    iosBundleId: 'com.nationalacademy.nationalAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyQ-jzGMcvBm4a4rKZjXiCyam16KNXKRI',
    appId: '1:450723447835:ios:aadad851989dd175b764be',
    messagingSenderId: '450723447835',
    projectId: 'national-academy-c0441',
    storageBucket: 'national-academy-c0441.firebasestorage.app',
    iosClientId: '450723447835-5avf10vt5v9ddfcj10781ku5ia0q8bnj.apps.googleusercontent.com',
    iosBundleId: 'com.nationalacademy.nationalAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLAXCUIQAsC_0oAxc9GHcaJsZKMVWezBA',
    appId: '1:450723447835:web:dbde6aebf35919b1b764be',
    messagingSenderId: '450723447835',
    projectId: 'national-academy-c0441',
    authDomain: 'national-academy-c0441.firebaseapp.com',
    storageBucket: 'national-academy-c0441.firebasestorage.app',
    measurementId: 'G-0R36ZCE6D0',
  );
}
